#!/bin/sh

set -e

for f in *.rs; do
  echo "$f"
  if [ "$f" = attribute.rs ]; then
      FLAGS=--test
      continue
  else
      FLAGS=
  fi
  rustc -L .. "$f" $FLAGS
  ./${f%%.rs}
  rm ${f%%.rs}
done
